[package]
name = "i3ypml"
version = "0.1.1"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1", features = ["full"] }
serde_json = "1"
lrc = "0.1.7"
regex = "1.5"